# Generated by Django 4.0.1 on 2022-02-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('ticker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('currency_code', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('ticker_name', models.TextField(blank=True, null=True)),
                ('ticker_fullname', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'universe',
                'managed': False,
            },
        ),
    ]
