# Generated by Django 4.0.1 on 2022-02-04 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_agreements_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='agreements',
            constraint=models.UniqueConstraint(fields=('user', 'agrement_type'), name='unique_agreement_user'),
        ),
    ]
