# Generated by Django 4.0.1 on 2022-02-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_agreements_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreements',
            old_name='agrement_type',
            new_name='agreement',
        ),
    ]
