# Generated by Django 4.0.1 on 2022-02-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_agrement_type_agreements_agreement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agreements',
            name='unique_agreement_user',
        ),
        migrations.AddField(
            model_name='bankaccounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='agreements',
            constraint=models.UniqueConstraint(fields=('user', 'agreement'), name='unique_agreement_user'),
        ),
    ]
