# Generated by Django 4.0.1 on 2022-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_bankaccounts_bank_code_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='email_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
