# Generated by Django 4.0 on 2022-01-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_botorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botorder',
            name='bot_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='botorder',
            name='investment_amount',
            field=models.FloatField(),
        ),
    ]
