# Generated by Django 4.0 on 2022-01-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_botorder_bot_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botorder',
            old_name='managed_asset_symbol',
            new_name='ric',
        ),
    ]
