# Generated by Django 4.0 on 2022-01-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_managed_asset_symbol_botorder_ric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botorder',
            name='bot_balance',
            field=models.FloatField(default=0),
        ),
    ]
