# Generated by Django 4.0 on 2022-01-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_botorder_bot_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='botorder',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botorder',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botorder',
            name='is_executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botorder',
            name='max_loss_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='botorder',
            name='max_loss_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='botorder',
            name='spot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botorder',
            name='target_profit_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='botorder',
            name='target_profit_pct',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='botorder',
            name='target_profit_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
