# Generated by Django 4.0 on 2022-01-14 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_botorder_executed_at_botorder_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botorder',
            name='asset_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botorder',
            name='asset_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BotAction',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('order_broker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('invested', models.FloatField(default=0)),
                ('executed_price', models.FloatField(default=0)),
                ('from_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='services.botorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
