# Generated by Django 4.0 on 2022-01-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_botorder_asset_id_botorder_asset_type_botaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='botaction',
            name='qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='botorder',
            name='current_bot_share',
            field=models.FloatField(default=0),
        ),
    ]
