# Generated by Django 4.0 on 2022-01-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_botaction_qty_botorder_current_bot_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botorder',
            old_name='current_bot_share',
            new_name='bot_holding_share',
        ),
    ]
