# Generated by Django 4.0.1 on 2022-02-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trade_status',
            field=models.BooleanField(default=False),
        ),
    ]
